services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak-ciba
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: debug,org.hibernate:info
      SPI_ACCESS_TOKEN_FORMAT_OPAQUE_ENABLED: "true"
    command: 
      - start-dev
      - "--spi-access-token-format-opaque-enabled=true"

   