services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: keycloak-dpop
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: info,org.keycloak.protocol.oidc.grants.ciba:trace,org.apache.http:trace
      KC_FEATURES: dpop
    command: 
      - start-dev
      - --import-realm
    volumes:
      - ./realm:/opt/keycloak/data/import 