services:
  postgres:
    image: postgres:15
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: secret
    volumes:
      - keycloak-db:/var/lib/postgresql/data
    networks:
      - keycloak-net

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: 
      - start
      - --features=scripts
    ports:
      - "8080:8080"
      - "8443:8443" 
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: secret
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/keystore.p12
      KC_HTTPS_CERTIFICATE_KEY_STORE_PASSWORD: changeit
      KC_HTTPS_CERTIFICATE_KEY_STORE_FILE: /opt/keycloak/certs/keystore.p12
      KC_HTTPS_CERTIFICATE_KEY_STORE_TYPE: PKCS12
      KC_HTTPS_KEY_STORE_PASSWORD: changeit
      KC_HTTPS_KEY_STORE_TYPE: PKCS12
      KC_HTTPS_KEY_STORE_FILE: /opt/keycloak/certs/keystore.p12
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"   # pour accéder aussi en HTTP si tu veux
      # Authenticator X509 pour browser Flow
      KC_SPI_AUTHENTICATOR_X509_CLIENT_CERTIFICATE_ENABLED: true
      JAVA_OPTS_APPEND: -Djavax.net.ssl.trustStore=/opt/keycloak/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit
      KC_HTTPS_CLIENT_AUTH: request
      KC_LOG_LEVEL: info,org.keycloak.authentication:trace,org.apache.http.wire:trace
      KC_FEATURES: dpop
    volumes:
      - ./keycloak-certs:/opt/keycloak/certs:ro
      - ./truststore.jks:/opt/keycloak/truststore.jks
      - ./theme:/opt/keycloak/themes
    depends_on:
      - postgres
    networks:
      - keycloak-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "81:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - keycloak-net

volumes:
  keycloak-db:
  pgadmin-data:

networks:
  keycloak-net:
