services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak-ciba
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: info,org.keycloak.protocol.oidc.grants.ciba:trace,org.apache.http:trace
    command: >
      start-dev
      --spi-ciba-auth-channel-ciba-http-auth-channel-http-authentication-channel-uri=http://localhost:8082/
    network_mode: host
    volumes:
      - ./realm:/opt/keycloak/data/import 