global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'keycloak-node1'
    static_configs:
      - targets: ['172.30.0.11:8080']
        labels:
          instance: keycloak-node1

  - job_name: 'keycloak-node2'
    static_configs:
      - targets: ['172.30.0.12:8080']
        labels:
          instance: keycloak-node2
