services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap-server
    command: --copy-service
    environment:
      LDAP_ORGANISATION: "CYBERLAB"
      LDAP_DOMAIN: "cyberlab.local"
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
      - "389:389"
    volumes:
      # Attention : ne pas monter tout le dossier /ldif, juste le fichier
      - ./ldap/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
    networks:
      - keycloak-ldap-net

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap-server
    ports:
      - "6443:443"
    networks:
      - keycloak-ldap-net

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak-ldap
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: secret
      KC_LOG_LEVEL: info,org.keycloak.storage.ldap:debug,org.keycloak.storage.ldap.idm.store:trace
    ports:
      - "8080:8080"
    depends_on:
      - ldap
    networks:
      - keycloak-ldap-net

  postgres:
    image: postgres:15
    container_name: keycloak-ldap-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: secret
    volumes:
      - keycloak-ldap-db:/var/lib/postgresql/data
    networks:
      - keycloak-ldap-net

networks:
  keycloak-ldap-net:

volumes:
  keycloak-ldap-db:
