FROM quay.io/keycloak/keycloak:24.0.2

USER root
# Ajout de l’ensemble des jars FIPS nécessaires
ADD https://repo1.maven.org/maven2/org/bouncycastle/bc-fips/2.0.0/bc-fips-2.0.0.jar /opt/keycloak/fips-libs/bc-fips.jar
ADD https://repo1.maven.org/maven2/org/bouncycastle/bctls-fips/2.0.20/bctls-fips-2.0.20.jar /opt/keycloak/fips-libs/bctls-fips.jar
ADD https://repo1.maven.org/maven2/org/bouncycastle/bcpkix-fips/2.0.8/bcpkix-fips-2.0.8.jar /opt/keycloak/fips-libs/bcpkix-fips.jar
ADD https://repo1.maven.org/maven2/org/bouncycastle/bcutil-fips/2.0.3/bcutil-fips-2.0.3.jar /opt/keycloak/fips-libs/bcutil-fips.jar

USER keycloak
# Dossier de config FIPS (optionnel)
COPY fips-java.security /opt/keycloak/conf/fips-java.security